{% set version = "2.2.0" %}

package:
  name: swagger-spec-validator
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/Yelp/swagger_spec_validator/archive/v{{ version }}.tar.gz
  sha256: dc191b145c1665372a33db8712e2b2cdf8873e6b84e9854fabe02848b9f3c83e

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - yaml

  run:
    - python
    - jsonschema
    - six
    - setuptools
    - yaml

test:
  imports:
    - swagger_spec_validator

about:
  home: http://github.com/Yelp/swagger_spec_validator
  license: Apache-2.0
  summary: 'Validation of Swagger specifications'
  license_family: APACHE
  license_file: LICENSE.txt
  dev_url: http://github.com/Yelp/swagger_spec_validator
  doc_url: http://swagger-spec-validator.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
