{% set version = "3.0.0" %}

package:
  name: swagger-spec-validator
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/Yelp/swagger_spec_validator/archive/v{{ version }}.tar.gz
  sha256: d0389e71be9df6e5beadd81164a3a0573af413d351ea9d86d84d23aa74a2c1f3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - pyyaml

  run:
    - python >=3.6
    - jsonschema
    - six
    - setuptools
    - pyyaml

test:
  imports:
    - swagger_spec_validator

about:
  home: http://github.com/Yelp/swagger_spec_validator
  license: Apache-2.0
  summary: Validation of Swagger specifications
  license_family: APACHE
  license_file: LICENSE.txt
  dev_url: http://github.com/Yelp/swagger_spec_validator
  doc_url: http://swagger-spec-validator.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
