{% set version = "2.4.2" %}

package:
  name: swagger-spec-validator
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/Yelp/swagger_spec_validator/archive/v{{ version }}.tar.gz
  sha256: e7c3ab4015cdbbf658bbeffd478a8e501158c7837e6a0152b7c90d3c9e7cd270

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - jsonschema
    - six
    - setuptools
    - pyyaml

test:
  imports:
    - swagger_spec_validator

about:
  home: http://github.com/Yelp/swagger_spec_validator
  license: Apache-2.0
  summary: 'Validation of Swagger specifications'
  license_family: APACHE
  license_file: LICENSE.txt
  dev_url: http://github.com/Yelp/swagger_spec_validator
  doc_url: http://swagger-spec-validator.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
