{% set version = "2.7.4" %}

package:
  name: swagger-spec-validator
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/Yelp/swagger_spec_validator/archive/v{{ version }}.tar.gz
  sha256: 7ff5779c0d7d8a6d697fdb9864df60780c27833c95f7850a6ade28e8d8eac1af

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - jsonschema
    - six
    - setuptools
    - pyyaml

test:
  imports:
    - swagger_spec_validator

about:
  home: http://github.com/Yelp/swagger_spec_validator
  license: Apache-2.0
  summary: Validation of Swagger specifications
  license_family: APACHE
  license_file: LICENSE.txt
  dev_url: http://github.com/Yelp/swagger_spec_validator
  doc_url: http://swagger-spec-validator.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
