travis:
  secure:
    BINSTAR_TOKEN: b2gPOS5jSfoiIag+jGCbe9UqD+35/f0mPWRMpvIdHGhVo+DBkymprey8eKKLgomEAR8Hd8mgqwKC3YaGVWSOjc3yzS+fP3wNVfPr8D3MASmRdhQhVZU8BBScKUBx9Tdq1oPaiT19w1bgxK/J/yjRRyYU54Lo/5BeNNbTHezfjCqfo+z5FqTU9vfrjOVikl0sBxrHncJ0/tx3m9L6MvpfSJsp1G/itpbaDfiCzy0EynM3RYQz0bwDmMxOB7gVKLkTOmkp2HMH2//aPklcILcP8b6FmgnDHAxbrK+DXZFGiiJrsVAskhPf1FelKMOFDr15SQEflbon8zUiR1/9ZN3xd87iQL5FO47pBj6otzeZybcTKwch+nrxSmCypbKCrN99FTZJhuDgarW4rHnjBdOWmSzLQiaIb0vd0F7WAFGcRoWyB4OVx5nwBm2JA9azmdMYE0Hfr3LNiVGyVIau8/HSgTDqRxpbDTi3wxEBB+adMrzbxq6Cw2Ls59Jl/lR/OPi2+t13oS6SzgYwoebm6bFHjMVJ7fSCS6R22fbISXI1qjg94/f0DCEmCuYqAdkns8+x5CzxVIxsktcXq46MvsqfC/gt9XQLXXmUJGtH/6LYLE5bn9CIUcHliGr5/Eq3DlkMsvv6KiHCPJIL2Pjj8ILbE5NAgc9NLIDiJoHC7J8Vpzs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
