travis:
  secure:
    BINSTAR_TOKEN: CnDJOKPer2L4GBBcbLuWt1fhQTaRhsYjPJS8w3mcvg6SXPqcivDfGLU+EjIpkCro2HqBgv7ccMCGgYpoTFF7rijFbyk4CzgCQLaOiWJZVrvwy+CGTINsLrYjR6xPdUF+bPAoAuI79fFZivfB6jAriOWOh9jUEF4AlaNF/r4VJr8qBKGLdyjfFWAe31aFTBnVIsiMCa6Qf46qwDBlfMLfBlWmFavPsP6sNH51hIE4JLBIEerFblwwTEXg8ogDYciXh9dGXe4jHE/FtUZAeARQziyYw/sU9UGwga1XDEtyEwyxV/7JRYVxpZAnzkMgjNzazEJuRilYF+FYmftdhrdZDPX6Q7Yv6OE+qm9zyaaVxhlFzQAUrFowybdEINw1Wlsjegdjop3+FnSiRY0mGp92u+K9fBND6yid/+lW4wrlQ6lRJYs13aUcu2TYGnlZXw7DYiDHU6cvNz3l9nHNDkNffeyxtRmG7bZLXJCcjT6ckcRTKEWCGd0jiaA1RU6sBTLv7dvlXNlk3rPEz+awk4PbBRcryXCVsvyuaAjHOCDzDczX85CJHg+gAkir5nVTmyl41WuhTw1iVIxqGm/UYN9PXomzBm4t//jAjqGnda+aEGnyLPYuXAlQTyXvEgVc8GFOLBU5CU0p7CUUN9BF5gZYgmCyiVTEVOqwgwkr/B/OGQ8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
